// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

struct cell
{
    uint2 position;
    float4 color;
    float4 material;
};

StructuredBuffer<cell> cells_to_add;

RWTexture2D<float4> result;
Texture2D last_update;
RWTexture2D<float4> material_map;

[numthreads(1, 1, 1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    cell c = cells_to_add[id.x];
    result[c.position] = c.color;
    material_map[c.position] = c.material;
}
